### PR TITLE
converting Vec2/Vec3 to static usage

### PR DESCRIPTION
**Pull request by mreinstein**
changes:
* convert `Vec2` from a class to a pile of exported functions
* replace all usage of `new VecX(...)` with `VecX.create(...)`
* rename `VecX.neo` to `VecX.create`
* convert the entire codebase to reference `Vec2Value` for all data references
* add `Vec2.scale`, `Vec2.copy`
* drop unused overloaded functions in `Vec2`

### CODE REVIEW

**Comment by shakiba** [comment]
Thanks for the PR.

Given the scope of your goal, I wonder what's your opinion about implementing all the changes in a fork, and eventually applying the key changes here? It could also inform our API design for the next major release if scope of changes is not trivial.

Also, as discussed before, Vec2 will be phased out sooner or later, so I prefer not to change it in the meantime.

**Comment by mreinstein** [comment]
> what's your opinion about implementing all the changes in a fork

Maybe I misunderstand, but isn't that what we're already doing?  I've got my changes in the mreinstein/planck.js fork and this PR is to merge it into piqnt/planck.js.  

> Also, as discussed before, Vec2 will be phased out sooner or later

I'm confused, I don't recall talking about Vec2 being phased out.  What will it be replaced with?

**Comment by shakiba** [comment]
> What will it be replaced with?

From [discord](https://discord.com/channels/598991238900875265/598991238900875268/1297612601563549799): There are new functions in common/Matrix which will replace Vec2 (and other similar classes) in the future. The new functions are already used in many places.

> Maybe I misunderstand, but isn't that what we're already doing? I've got my changes in the mreinstein/planck.js fork and this PR is to merge it into piqnt/planck.js.

You are mostly right. On discord you mentioned "something to note is this isn't the full set of changes that would be needed.  I figured for the first PR, I'd keep it to just the constructor related changes", "And I wanted to limit the size of the initial PR to get a sanity check before I go all in on the rest of the changes", and before you mentioned your final goal is being able to use ts-morph to support array notation.

What I meant is to first have your entire solution (all the changes and additions) in mreinstein/planck.js, and then we can figure out what are the necessary changes in the library to support your use-case. This way we can see the big picture and make an informed decision; we can decide a proper release plan (if they are trivial we can release in v1, otherwise postpone until next major release); and you could freely change the code until you achieve your goal.

**Comment by shakiba** [comment]
We won't be able to remove things from the API without major version change, but I guess it makes sense to remove depreciated stuff in your branch.

**Comment by mreinstein** [comment]
Alright I will just go full-nuclear in my fork then.  Do you think we can publish this v2.x? Might as well rip off the bandaid.

**Comment by shakiba** [comment]
We will definitely take a look to see what could we merge in

**Comment by mreinstein** [comment]
@shakiba I'd like to get some eyes on this please.

still to do:
* fix serialize/de-serialize capability
* go through every single test bed example and compare my fork to the pinqt/planck testbed to ensure no errors or visible behavior deviation
* update all the docs to match the new reality

**Comment by mreinstein** [comment]
Am I on the right track with this?

**Comment by shakiba** [comment]
@mreinstein I appreciate your effort; before we could see your array project built using the proposed changes here unfortunately I won't be able to have any opinion.

**Comment by mreinstein** [comment]
@shakiba why are these changes predicated on having my array notation idea completed?  These changes are meant to stand on their own as improvements to planck.  Namely, having a consistent, data oriented vector API.

**Comment by mreinstein** [comment]
The way I've been envisioning it is a 2 step process:
1. update the Vec2/Vec3 to use static functions _everywhere_, which means a simplified API, and having pure data passed around rather than a class implementation. Get this released into a planck v2
2. using `planck@2` as a starting point, develop an automated transform that can replace all Vector usage from object to array notation

I'm planning/hoping that we could get through `Step 1` first, because even without `Step2` it still improves planck for everyone, even people that continue to use vector object notation.

does that make sense to you too?

**Comment by shakiba** [comment]
> These changes are meant to stand on their own as improvements

Without context I neither agree nor disagree with proposed changes. You are welcome to have your opinion, and fork the library and make it better.

**Comment by mreinstein** [comment]
> Without context I neither agree nor disagree with proposed changes. You are welcome to have your opinion, and fork the library and make it better.

This really doesn't sound like you're willing to work with me on this. Again: I'm trying to split this work into 2 chunks, so that I don't need to put in 60 hours up-front and get to the end of it with an answer that is essentially no.  

This PR is chunk 1. tries to improve the following for `vec2`/`vec3`:
1. make the API consistent, so that for example there is not a different behavior for `a.add(b)` vs  `Vec2.add(a, b)`
2. make vectors data only, instead of having to attach dozens of methods and state to every single one
3. combine some duplicate functions like `new Vec2()`, `Vec2.neo()` so there is 1 consistent way to create vectors 
4. add some additional common vector functions, like `Vec2.copy` and `Vec2.scale`
5. pave the way for easier code parsing in some later release (for array notation for example)

Chunk 2 would be the array notation exploration. It is out of scope for this PR.  I'm doing this explicitly to split the work out into releasable pieces, because mega PRs are harder to actually release compared to small targeted pieces.  We should be releasing smaller pieces more often, and delivering value with each release. That is what these 2 chunks attempt to do.

**Pull request closed without merging**
